app/blueprints/api/routes.py
from app.blueprints.authentication.auth import basic_auth, token_auth
from flask import Blueprint, request, jsonify
from models import User, Post, Chart
from forms import PostForm
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user


api = Blueprint('api',__name__, url_prefix='/api')


@api.route('/create-post', methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        # Get data from form
        brand = form.brand.data
        name = form.name.data
        size = form.size.data
        price = form.price.data
        #Create new post instance which will also add to db
        new_post = Post(brand=brand, name=name, size=size, price=price, user_id=current_user.id)
        flash(f"{new_post.brand} has been created", "success")
        return redirect(url_for('site.index'))
        
    return render_template('create.html', form=form)

@api.route('/posts/<int:post_id>')
@login_required
def get_post(post_id):
    # post = Post.query.get_or_404(post_id)
    post = Post.query.get(post_id)
    if not post:
        flash(f"A post with id {post_id} does not exist", "danger")
        return redirect(url_for('site.index'))
    return render_template('post.html', post=post)


@api.route('/posts/<post_id>/edit', methods=["GET", "POST"])
@login_required
def edit_post(post_id):
    post = Post.query.get(post_id)
    if not post:
        flash(f"A post with id {post_id} does not exist", "danger")
        return redirect(url_for('site.index'))
    # Make sure the post author is the current user
    if post.author != current_user:
        flash("You do not have permission to edit this post", "danger")
        return redirect(url_for('site.index'))
    form = PostForm()
    if form.validate_on_submit():
        # Get the form data
        brand = form.brand.data
        name = form.name.data
        size = form.size.data
        price = form.price.data
        # update the post using the .update method
        post.update(brand=brand, name=name, size=size, price=price, user_id=current_user.id)
        flash(f"{post.brand} has been updated!", "success")
        return redirect(url_for('api.get_post', post_id=post.id))
    if request.method == 'GET':
        form.brand.data = post.brand
        form.name.data = post.name
        form.size.data =post.size
        form.price.data =post.price
    return render_template('edit.html', post=post, form=form)

# DELETE car ENDPOINT

@api.route('/posts/<post_id>/delete')
@login_required
def delete_post(post_id):
    post = Post.query.get(post_id)
    if not post:
        flash(f"A post with id {post_id} does not exist", "danger")
        return redirect(url_for('site.index'))
    # Make sure the post author is the current user
    if post.author != current_user:
        flash("You do not have permission to delete this post", "danger")
        return redirect(url_for('site.index'))
    post.delete()
    flash(f"{post.brand} has been deleted", "info")
    return redirect(url_for('site.index'))



#API routes

@api.route('/token')
@basic_auth.login_required
def index_():
    user = basic_auth.current_user()
    token = user.get_token()
    return {'token':token, 'token_expiration':user.token_expiration}

@api.route('/users')
@token_auth.login_required
def get_user():
    user = token_auth.current_user()
    return jsonify([user.to_dict()])

@api.route('/users', methods=['POST'])
def createuser():
    if not request.is_json:
        return("your request content-type is not JSON"), 400
    data=request.json
    for field in ['email', 'username', 'password']:
        if field not in data:
            return("error:f{field} must be in request body"), 400
    email = data.get('email')
    username = data.get("username")
    password = data.get('password')
            # Query our user table to see if there are any users with either username or email from form
    check_user = User.query.filter( (User.username == username) | (User.email == email) ).all()
        # If the query comes back with any results
    if check_user:
        return ('A user with that email and/or username already exists.'), 400
    new_user = User(email=email, password=password, username= username)
    return new_user.to_dict(), 201
    
@api.route('/user/edit/<int:user_id>', methods=['POST'])
def edit_user(user_id):
    user = User.query.get(user_id)
    if not request.is_json:
        return("your request content-type is not JSON"), 400
    data=request.json
    for field in ['username','email', 'password']:
        if field not in data:
            return("error:f{field} must be in request body"), 400
    username = data.get('username')
    password = data.get("password")
    email = data.get("email")
    same_user =  token_auth.current_user()
    user.update(username=username, email=email, password=password, user_id=same_user)
    return user.to_dict()


@api.route('/user/delete/<int:user_id>', methods=['POST'])
def delete_user(user_id):
    user = User.query.get(user_id)
    if not request.is_json:
        return("your request content-type is not JSON"), 400
    data=request.json
    for field in ['username']:
        if field not in data:
            return("error:f{field} must be in request body"), 400
    user.delete()
    return user.to_dict(), 201

@api.route('/posts', methods=['GET'])
def getposts():
    posts = Post.query.all()
    return jsonify([p.to_dict() for p in posts])

@api.route('/post/<int:post_id>')
def getpost(post_id):
    posts = Post.query.get(post_id)
    return posts.to_dict()

@api.route('/posts', methods=['POST'])
def createpost():
    if not request.is_json:
        return("your request content-type is not JSON"), 400
    data=request.json
    for field in ["brand", "name", 'size', "price"]:
        if field not in data:
            return(f"error:{field} must be in request body"), 400
    brand = data.get('brand')
    name=data.get('name')
    size = data.get("size")
    price=data.get('price')
    user =  token_auth.current_user()
    new_post = Post(brand=brand, name=name, price=price, size=size, user_id=user)
    return new_post.to_dict(), 201
    
@api.route('/post/edit/<int:post_id>', methods=['POST'])
def editpost(post_id):
    post = Post.query.get(post_id)
    if not request.is_json:
        return("your request content-type is not JSON"), 400
    data=request.json
    for field in ['brand','name', 'size', 'price']:
        if field not in data:
            return("error:f{field} must be in request body"), 400
    brand = data.get('brand')
    name=data.get('name')
    size = data.get("size")
    price=data.get('price')
    user =  token_auth.current_user()
    post.update(brand=brand, name=name, size=size, price=price, user_id=user)
    return post.to_dict(), 201


@api.route('/post/delete/<int:post_id>', methods=['POST'])
@token_auth.login_required
def deletepost(post_id):
    post = Post.query.get(post_id)
    if not request.is_json:
        return("your request content-type is not JSON"), 400
    data=request.json
    for field in ['brand', 'name', 'size', 'price']:
        if field not in data:
            return("error:f{field} must be in request body"), 400
    post.delete()
    return post.to_dict(), 201

@api.route('/cart', methods=['GET'])
def getitems():
    chart = Chart.query.all()
    return jsonify([c.to_dict() for c in chart])

@api.route('/chart<int:chart_id>', methods=['GET'])
def getitem(chart_id):
    chart = Chart.query.get(chart_id)
    return chart.to_dict()

@api.route('/chart/delete/<int:chart_id>', methods=['POST'])
def delete_item(chart_id):
    chart = Chart.query.get(chart_id)
    if not request.is_json:
        return("your request content-type is not JSON"), 400
    data=request.json
    for field in ["brand", 'name', 'size', 'price']:
        if field not in data:
            return("error:f{field} must be in request body"), 400
    chart.delete()
    return chart.to_dict(), 201

@api.route('/chart/empty', methods=['POST'])
def empty_chart():
    chart = Chart.query.all()
    chart.delete_all()
    return chart.to_dict(), 201

@api.route('/chart/create', methods=['POST'])
def create_chart():
    if not request.is_json:
        return("your request content-type is not JSON"), 400
    data=request.json
    for field in ["brand","size", "name", "price"]:
        if field not in data:
            return(f"error:{field} must be in request body"), 400
    brand=data.get("brand")
    name=data.get('name')
    size = data.get("size")
    price=data.get('price')
    user =  token_auth.current_user()
    new_chart = Chart(brand=brand, name=name, price=price, size=size, user_id=user)
    return new_chart.to_dict(), 201

app/blueprints/authentication/routes.py
from forms import LoginForm, SignUpForm
from models import User, db
from flask import Blueprint, render_template, redirect, url_for, flash
from flask import render_template, redirect, url_for, flash
from flask_login import login_user, logout_user

# imports for flask login 
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods=["GET", "POST"])
def signup():
    # Create an instance of the SignUpForm
    form = SignUpForm()
    # Check if a POST request AND data is valid
    if form.validate_on_submit():
        print('Form Submitted and Validated!')
        # Get data from the form
        email = form.email.data
        username = form.username.data
        password = form.password.data
        print(email, username, password)
        # Query our user table to see if there are any users with either username or email from form
        check_user = User.query.filter( (User.username == username) | (User.email == email) ).all()
        # If the query comes back with any results
        if check_user:
            # Flash message saying that a user with email/username already exists
            flash('A user with that email and/or username already exists.', 'danger')
            return redirect(url_for('auth.signup'))
        # If check_user is empty, create a new record in the user table
        new_user = User(email=email, username=username, password=password)
        # Flash a success message
        flash(f'Thank you {new_user.username} for signing up!', 'success')
        # Redirect back to Home
        return redirect(url_for('site.index'))

    return render_template('sign_up.html', form=form)



@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # Get the username and password from the form
        username = form.username.data
        password = form.password.data
        print(username, password)
        # Query the user table to see if there is a user with that username
        user = User.query.filter_by(username=username).first()
        # Check if there is a user and that the password is correct
        if user is not None and user.check_password(password):
            # log the user in
            login_user(user)
            flash(f"{user.username} is now logged in", "warning")
            return redirect(url_for('site.index'))
        else:
            flash("Incorrect username and/or password", "danger")
            return redirect(url_for('auth.login'))
        
    return render_template('login.html', form=form)

@auth.route('/logout', methods = ['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('site.index'))

app/blueprints/site/routes.py
from flask import Blueprint, render_template
from models import User, db, check_password_hash, Post
from flask import Blueprint, render_template, request, redirect, url_for, flash
from forms import LoginForm, PostForm

# imports for flask login 
from flask_login import login_user, logout_user, LoginManager, current_user, login_required


site = Blueprint('site', __name__, template_folder='site_templates')


@site.route('/', methods = ['GET', 'POST'])
def index():
    posts = Post.query.all()
    return render_template('index.html', posts=posts)

@site.route('/profile', methods = ['GET', 'POST'])
@login_required
def profile():
    form = PostForm()
    if form.validate_on_submit():
        # Get data from form
        brand = form.brand.data
        name = form.name.data
        size = form.size.data
        price=form.price.data
        # Create new post instance which will also add to db
        new_post = Post(brand=brand, name=name, price=price, size=size, img=image, user_id=current_user.id)
        flash(f"{new_post.brand} has been created", "success")
        return redirect(url_for('site.index'))
        
    return render_template('create.html', form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <title>Blessing's Shop | {% block title %} Hello {% endblock %}</title>
</head>
<body class="bg-success-subtle">
    
    {% include 'nav.html' %}

    <div class="container mt-5 p-3">
        {% block content %}
        {% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/templates/create.html
{% extends 'base.html' %}

{% block title %} Create A Post {% endblock %}

{% block content %}

<form action="" class="bg-white rounded mt-3 p-5" method="post">
    <h1 class="text-center">Post your article</h1>
    {{ form.csrf_token }}

    {{ form.image.label }}<br>{{ form.image }}
    <span class="validation_error">{{ ', '.join(form.image.errors) }}</span><br>

    {{ form.brand.label }}
    {{ form.brand(class='form-control', placeholder='Enter brand of article') }}

    {{ form.name.label }}
    {{ form.name(class='form-control', placeholder='Enter name of article') }}

    {{ form.size.label }}
    {{ form.size(class='form-control', placeholder='Enter size of article') }}

    {{ form.price.label }}
    {{ form.price(class='form-control', placeholder='Enter price of article in dollars') }}

    {{ form.submit(class='btn btn-primary w-100 mt-3') }}
</form>

{% endblock %}

app/templates/edit.html
{% extends 'base.html' %}

{% block title %} Edit {% endblock %}

{% block content %}

<form action="" class="bg-white rounded mt-3 p-5" method="post">
    <h1 class="text-center">Edit your article</h1>
    {{ form.csrf_token }}

    {{ form.image.label }}<br>{{ form.image }}
    <span class="validation_error">{{ ', '.join(form.image.errors) }}</span><br>

    {{ form.brand.label }}
    {{ form.brand(class='form-control', placeholder='Enter brand of article') }}

    {{ form.name.label }}
    {{ form.name(class='form-control', placeholder='Enter name of article') }}

    {{ form.size.label }}
    {{ form.size(class='form-control', placeholder='Enter size of article') }}

    {{ form.price.label }}
    {{ form.price(class='form-control', placeholder='Enter price of article in dollars') }}

    {{ form.submit(class='btn btn-primary w-100 mt-3') }}
</form>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

{% if current_user.is_authenticated %}
        <h1 class="text-center">Welcome Back, {{ current_user.username }}!</h1>
    {% for post in posts %}
        <div class="card my-3">
            <img src="" alt="{{ post.img }}">
            <div class="card-header">
            Brand: {{ post.brand }}
            </div>
            <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>name: {{ post.name }}</p>
                <p>size: {{ post.size }}</p>
                <p>price: ${{ post.price }}</p>
                <footer class="blockquote-footer">{{ post.author.username }} on
                    <cite title="Source Title">{{ post.date_created.strftime('%A, %B %d at %I:%M%p') }}</cite>
                </footer>
            </blockquote>
            <a href="{{ url_for('api.get_post', post_id=post.id) }}" class="btn btn-primary mt-3">See More</a>
            </div>
        </div>
    {% endfor %}
{% else %}
    <h1 class="text-center"><em><strong>Get the best deals and offers at prices that fits your budget</strong></em></h1>
    <div class="container-fluid">
        <div class="display-flex justify-content-center align-content-center">
        <a href="/login" class="btn btn-success m-auto">Get Started</a>
        </div>
    </div>
{% endif %}

{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
<form action="" class="bg-white rounded mt-5 p-5" method="post">
    <div class="row">
        <aside class="col-12 col-md-6">
            <h2>Sign In</h2>    
                {{ form.csrf_token }}
            
                {{ form.username.label }}
                {{ form.username(class='form-control', placeholder='Enter Username') }}
            
                {{ form.password.label }}
                {{ form.password(class='form-control', placeholder='Enter Password') }}
            
                {{ form.submit(class='btn btn-primary w-100 mt-3') }}
        </aside>
    </div>
</form>
{% endblock %}

app/templates/nav.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
    <div class="container">
          <a href="/" class="navbar-brand align-item-center">Blessing's Shopping Mart</a>
          <button 
              class="navbar-toggler" 
              type="button" 
              data-bs-toggle="collapse" 
              data-bs-target="#navmenu"
          ><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navmenu">
                  <ul class="navbar-nav ms-auto">
                      <li class="nav-item">
                          <a href="/" class="nav-link">Home</a>
                      </li>
                      {% if current_user.is_authenticated %}
                      <li class="nav-item">
                          <a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a>
                      </li>
                      <li class="nav-item">
                          <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                      {% else %}
                      <li class="nav-item">
                          <a href="{{ url_for('auth.login') }}" class="nav-link">Sign In</a>
                      </li>
                      <li class="nav-item">
                          <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
                      </li>
                      {% endif %}
                  </ul>
          </div>
    </div>
  </nav>

app/templates/post.html
{% extends 'base.html' %}

{% block title %} {{ post.brand }} {% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card my-3">
            <!-- <img src="https://picsum.photos/2500/500" class="card-img-top" alt="placeholder image"> -->
            <img src="data:image/jpeg;base64,{{ post.img }}" class="card-img-top" alt="">
            <div class="card-body">
                <h5 class="card-title">brand: {{ post.brand }}</h5>
                <p class="card-text">name: {{ post.name }}</p>
                <p class="card-text">size: {{ post.size }}</p>
                <p class="card-text">price: ${{ post.price }}</p>
                <p class="card-text"><small class="text-muted">{{ post.author.username }}</small></p>
                {% if current_user == post.author %}
                    <a href="{{ url_for('api.edit_post', post_id=post.id) }}" class="btn btn-success">Edit Post</a>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
                        Delete Post
                    </button>
                    
                    <!-- Modal -->
                    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="deleteModalLabel">Delete {{ post.brand }}?</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                Are you sure you want to delete {{ post.brand }}? This action cannot be undone.
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <a href="{{ url_for('api.delete_post', post_id=post.id) }}" class="btn btn-danger">Delete Post</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/sign_up.html
{% extends 'base.html' %}

{% block content %}
    <!-- Form content -->
    <main class="container p-5 mt-5">
        <div class="row">
            <aside class="col-12 col-md-6">
                <h2>Create Your Account</h2>
                <form action="" class="bg-white rounded mt-3 p-5" method="post">
                    <h1 class="text-center">Sign Up</h1>
                    {{ form.csrf_token }}
                    
                    {{ form.email.label }}
                    {{ form.email(class='form-control', placeholder='Enter Email') }}
                
                    {{ form.username.label }}
                    {{ form.username(class='form-control', placeholder='Enter Username') }}
                
                    {{ form.password.label }}
                    {{ form.password(class='form-control', placeholder='Enter Password') }}
                
                    {{ form.confirm_pass.label }}
                    {{ form.confirm_pass(class='form-control', placeholder='Confirm Password') }}
                
                    {{ form.submit(class='btn btn-primary w-100 mt-3') }}
                </form>
            </aside>
        </div>
    </main>
{% endblock %}